version: '3.8'

services:
  orchestrator:
    build:
      context: .
      dockerfile: orchestrator/Dockerfile
    ports:
      - "22555:22555/udp"

  dedicated_server:
    build:
      context: .
      dockerfile: dedicated_server/Dockerfile
    environment:
      - DS_PORT=7001
      - DS_ZONE=zone_A
      - MAX_PLAYERS=10
      - ORCH_ADDR=orchestrator:22555
    ports:
      - "7001:7001/udp"
    depends_on:
      - orchestrator

  gatekeeper:
    build:
      context: .
      dockerfile: gatekeeper/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - orchestrator