[package]
name = "dedicated_server"
version.workspace = true
edition.workspace = true

[dependencies]
shared.workspace = true
bevy.workspace = true
game_sockets.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
tokio.workspace = true
bytes = "1.11.1"
bincode = "1.3.3"